# Site settings
title: Matt Christians | My thoughts in markdown
description: "Matt Christians Blog, My Thoughts in Markdown"
url: "http://www.mdchristians.github.io"
author:
  name: "Matt Christians"
  url: "http://www.mdchristians.com"

# Build settings
baseurl: mdchristians.github.io/
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Custom variables
version: "1.0.1"
